name: Pullrequest Created

on:
  pull_request_target:
    branches: main

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
    # Send an informational status embed to Discord instead of the
    # standard embeds that Discord sends. This embed will contain
    # more information and we can fine tune when we actually want
    # to send an embed.
    - name: GitHub Actions Status Embed for Discord
      uses: SebastiaanZ/github-status-embed-for-discord@v0.3.0
      with:
        # Our GitHub Actions webhook
        webhook_id: '1077598245905252443'
        webhook_token: ${{ secrets.GHA_WEBHOOK_TOKEN }}
        status: "success"

        workflow_name: "HELLO THERE"
